config/routes.rb
Glittery::Application.routes.draw do
  root to: 'artworks#index'

  resource :admin do
    member do
      get 'password'
    end
  end 

  resource :artist

  resources :artworks

  resources :sessions, only: [:new, :create, :destroy]

  match 'login'  => 'sessions#new'
  match 'logout' => 'sessions#destroy', via: :delete

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :password, :username, :new_password, :password_confirmation,
                  :external
  has_secure_password
  has_one :artist, inverse_of: :admin

  # Validations:
 
  validates :username, presence: true, 
                       length: { minimum: 6, 
        too_short: "must be at least %{count} characters" }, 
                       uniqueness: true

  VALID_PASSWORD_REGEX = 
  /((?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@#\$\!]).{8,})/

  validates :password, presence: true, length: { minimum: 8,
        too_short: "must be at least %{count} characters" }, 
                       format: { with: VALID_PASSWORD_REGEX,
 message: "must contain at least one lowercase letter, at 
 least one capital letter, at least one number, and at least one of 
 the following: @#!$"},
                       confirmation: true

  validates_presence_of :password_confirmation

  validates_uniqueness_of :external, message: "can only be set for one admin"

  # Callbacks:

  before_create :create_remember_token

  after_create :create_artist

  # Class methods:
 
  def self.external_config_admin
    if File.exists?("config/admin.yml")
      file = Psych.load(File.open("config/admin.yml"))
      new_external_config_admin = Admin.new(username: file[:username], 
                                            password: file[:password],
                               password_confirmation: file[:password])
      File.delete("config/admin.yml")
      if new_external_config_admin.save
         # Maybe change to destroy to prevent unused records floating around?
         if current_config_admin = Admin.find_by_external(true)
           current_config_admin.toggle!(:external)
         end
         new_external_config_admin.toggle!(:external)
         new_external_config_admin
      end
    else
      Admin.find_by_external(true)
    end
  end
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :bio, :email, :name, :photo, :site_title, 
  has_attached_file(:photo, { url: '/artist/:filename' })

  belongs_to :admin, inverse_of: :artist
  has_many :artworks, dependent: :destroy

  validates :admin_id, presence: true
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, unless: "email.blank?"

  before_save do |artist|
    artist.name = "" if artist.name == nil
    artist.bio = "" if artist.bio == nil
    artist.site_title = "Glittery" if artist.site_title == nil
  end
end

app/models/artwork.rb
# == Schema Information
#
# Table name: artworks
#
#  id          :integer          not null, primary key
#  image       :attachment
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artwork < ActiveRecord::Base
  attr_accessible :description, :image, :name
  has_attached_file :image, styles: { full: '990x990>', gallery: '200x200' },  
                            url: '/art/:style/:filename', 
                            path: ':rails_root/public/art/:style/:filename'
  belongs_to :artist

  validates :image, attachment_presence: { if: :image, 
                      message: "^Please select an image to upload." }
end

app/models/session.rb
module Session
  class << self
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def edit
    if !signed_in?
      redirect_to 'login'
    end
  end

  def password
    if !signed_in?
      redirect_to 'login'
    end
  end

  def update
    if current_admin.update_attributes(password: 
                                       params[:admin][:new_password],
                                       new_password: nil,
                                       password_confirmation:
                               params[:admin][:password_confirmation])
      render 'edit' 
    else
      render 'password' 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Admin.external_config_admin.artist 
  end
  
  def edit
    if !signed_in? 
      redirect_to '/login'
    end
  end

  def update
    if current_admin.artist.update_attributes(params[:artist])
      redirect_to edit_admin_path
    else
      render 'edit'
    end
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @artworks = Artwork.all
  end

  def new
    if !signed_in?
      redirect_to '/login'
    end
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(params[:artwork])
    if @artwork.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @artwork = Artwork.find(params[:id])
  end
  
  def edit
    if !signed_in?
      redirect_to '/login'
    end
    @artwork = Artwork.find(params[:id])
  end

  def update
    @artwork = Artwork.find_by_id(params[:id])
    @artwork.update_attributes(params[:artwork])
    redirect_to '/'
  end

  def destroy 
    Artwork.find(params[:id]).destroy
    redirect_to '/' 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to edit_admin_path
    end

    Admin.external_config_admin
  end

  def create
    admin = Admin.find_by_username(params[:username])
    if admin && admin.authenticate(params[:password]) 
      sign_in(admin, params[:remember_me])
      redirect_to edit_admin_path 
    else
      flash.now[:error] = 'Wrong username/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_title
    Admin.external_config_admin.artist.site_title
  end

  def artist_has_no_info?
    artist = Admin.external_config_admin.artist
    if artist.name == "" && artist.bio == "" && 
    artist.photo_file_name == nil && artist.email.blank? 
      return true
    else
      return false
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(admin, perm_flag = false)
    if perm_flag
      cookies.permanent[:remember_token] = admin.remember_token
    else
      cookies[:remember_token] = admin.remember_token
    end
    current_admin = admin
  end

  def signed_in?
    if cookies[:remember_token]
      !current_admin.nil?
    end
  end

  def sign_out
    current_admin = nil
    cookies.delete(:remember_token)
  end

  def current_admin=(admin)
    @current_admin = admin
  end

  def current_admin
    @current_admin ||= 
    Admin.find_by_remember_token(cookies[:remember_token])
  end
end

app/views/admins/edit.html.erb
<h2>Administration</h2>
<div class="toolkit">
<a href='/'>Edit Gallery</a><br>
<%= link_to 'Change Info', edit_artist_path %><br>
<%= link_to 'Change Password', password_admin_path %><br>
</div>
<div id="logout">
<%= button_to('Log out', '/logout', method: 'delete') %>
</div>

app/views/admins/password.html.erb
<h2>Change Password</h2>
<%= form_for current_admin, url: { action: 'update' }, 
  html: { class: "form", id: "change_password" } do |a| %>
  <%= render partial: 'shared/errors', locals: { instance: current_admin }  %>

  <%= a.label      :new_password %>
  <%= a.password_field :new_password %><br>

  <%= a.label      :password_confirmation, 'Confirm password' %>
  <%= a.password_field :password_confirmation %><br>
<div class="submit">
  <%= a.submit "Submit" %>
</div>
<% end %>
<%= link_to 'back', edit_admin_path %>

app/views/artists/edit.html.erb
<h2>Change Info</h2>
<%= form_for current_admin.artist, url: { action: 'update' }, html: 
  { class: "form" } do |a| %>
  <%= render partial: 'shared/errors', 
  locals: { instance: current_admin.artist }  %>

  <%= a.label      :name %>
  <%= a.text_field :name %><br>

  <%= a.label      :email %>
  <%= a.text_field :email %><br>

  <%= a.label      :site_title %>
  <%= a.text_field :site_title %><br>

  <%= a.label      :photo %>
  <%= a.file_field :photo %><br>
 
<div class="text">
  <%= a.label      :bio %>
  <%= a.text_area :bio %><br>
</div>

<div class="submit">
  <%= a.submit 'Submit'%><br>
</div>
<% end %>
<%= link_to 'back', edit_admin_path %>

app/views/artists/show.html.erb
<div id="artist_info">
  <% unless @artist.name == "" %>
    <h2 id="name"><%= @artist.name %></h2>
  <% end %>
  <% unless @artist.photo_file_name == nil %>
    <%= image_tag @artist.photo.url %>
  <% end %>
  <% unless @artist.bio == "" %>
    <div id="bio">
      <div id="bio_container">
      <%= simple_format h( @artist.bio ) %>
      </div>
    </div>
  <% end %>
  <% unless @artist.email.blank? %>
    <p id="email">
      <%= link_to "contact me", "mailto:#{@artist.email}" %>
    </p><br>
  <% end %>
  <a href="/">back</a>
</div>

app/views/artworks/edit.html.erb
<%= image_tag @artwork.image.url(:gallery) %>
<%= form_for @artwork, url: { action: 'update' }, 
  html: { class: 'artwork_form' } do |a| %>
  <%= a.label      :name %>
  <%= a.text_field :name %><br>

  <%= a.label      :image %>
  <%= a.file_field :image %><br>

  <%= a.label      :description %><br>
  <%= a.text_area  :description, size: '50x15' %><br>

  <%= a.submit 'Submit' %>
<% end %>
<%= link_to 'back', '/' %>

app/views/artworks/index.html.erb
<nav>
  <% if signed_in? %>
    <%= link_to 'Add New Artwork', new_artwork_path %><br>
    <%= link_to 'Settings', edit_admin_path %>
  <% end %>
</nav>
<div id="gallery">
  <% @artworks.each do |artwork| %>
    <div class="art">
      <div id="<%= artwork.name %>">
        <div class="artwork_heading">
          <h3><%= artwork.name %></h3><br>
        </div>
        <div class="image">
          <%= link_to artwork do %>
            <%= image_tag artwork.image.url(:gallery) %>
          <% end %>
          <br>
        </div>
        <% if signed_in? %>
          <div class="edit_links">
            <%= link_to 'Edit', edit_artwork_path(artwork.id) %><br>
            <%= link_to 'Delete', artwork, 
              method: 'delete', confirm: 'Are you sure?' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/artworks/new.html.erb
<h2>Add New Artwork</h2>
<p>Adding a name and/or description is optional.</p>
<%= form_for @artwork, url: { action: 'create' }, 
  html: { class: 'artwork_form' } do |a| %>
  <%= render partial: 'shared/errors', locals: { instance: @artwork }  %>

  <%= a.label      :image %>
  <%= a.file_field :image %><br>

  <%= a.label      :name %>
  <%= a.text_field :name %><br>

  <%= a.label     :description %><br>
  <%= a.text_area :description %><br>

  <%= a.submit 'Submit' %>
<% end %>
<%= link_to 'back', '/' %>

app/views/artworks/show.html.erb
<div id="single_art">
  <h2><%= @artwork.name %></h2>
  <%= image_tag @artwork.image.url(:full) %>
  <div id="description_of_artwork">
    <%= simple_format h( @artwork.description ) %>
  </div>
<a href="/">back</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= site_title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="<%= Rails.root.to_s + 
    'app/assets/javascripts/html5shiv.js' %>"</script>
  <![endif]-->
</head>
<body>
  <header id="header">
    <h1><%= site_title %></h1>

  <% unless artist_has_no_info? || request.fullpath == '/artist' %>
    <%= link_to "bio", artist_path %>
  <% end %>
  </header>

    <div class="flash_box">
      <% flash.each do |key, value| %>
        <div class="flash"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
  <div id="errors">
    <% instance.errors.full_messages.uniq.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %> 